name: first

on: push

jobs:
       jobs1:
                name: First Job
                runs-on: ubuntu-latest
                steps:
                 - name: Step one
                steps:
                 - name: Step one 
                   uses: actions/checkout@v2
                 - name: Step two
                   run: env | sort
       jobs2:
                name: First Job
                runs-on: windows-latest
                steps:
                 - name: Step one 
                   uses: actions/checkout@v2
                 - name: Step two
                   run: "Get-Childitem Env: | Sort-Objects Name" 